export const mockColaboradores = [
  {
    idClientePrincipal: 636,
    idPerfilClientePrincipal: 1,
    idClienteFavorecido: 558,
    idPerfilClienteFavorecido: 2,
    dataInclusao: "2023-09-26T14:42:57",
    dataCancelamento: "2023-11-08T14:00:59",
    nome: "CPF Teste 1",
    email: "wfernandoaugusto01@gmail.com",
    sexo: "M",
    dataNascimento: "1993-07-27",
    telefone: "21966744479",
    numeroDocumento: "09301823080",
    solicitarSegundaVia: false,
    solicitarPrimeiraVia: false,
    pedidoCartao: false,
    matricula: "0003",
    valorUsoDiario: 10,
    valorUsoDiarioRefeicao: 0,
    valorAlimentacao: 0,
    valorCombustivel: 0,
    numeroLogicoMidia: 0,
    tipoDePedido: "",
    valorDaRecarga: 0,
  },
  {
    idClientePrincipal: 636,
    idPerfilClientePrincipal: 1,
    idClienteFavorecido: 635,
    idPerfilClienteFavorecido: 2,
    dataInclusao: "2023-09-26T14:21:37",
    dataCancelamento: "2023-11-08T14:01:07",
    nome: "CPF Teste 13",
    email: "wfernandoaugusto01@gmail.com",
    sexo: "M",
    dataNascimento: "1993-07-27",
    telefone: "21966734447",
    numeroDocumento: "62534237039",
    solicitarSegundaVia: false,
    solicitarPrimeiraVia: true,
    pedidoCartao: false,
    matricula: "0002",
    valorUsoDiario: 10,
    valorUsoDiarioRefeicao: 0,
    valorAlimentacao: 0,
    valorCombustivel: 0,
    numeroLogicoMidia: 0,
    tipoDePedido: "",
    valorDaRecarga: 0,
  },
  {
    idClientePrincipal: 636,
    idPerfilClientePrincipal: 1,
    idClienteFavorecido: 637,
    idPerfilClienteFavorecido: 2,
    dataInclusao: "2023-09-26T14:54:06",
    dataCancelamento: "2023-11-08T13:29:10",
    nome: "CPF Teste ",
    email: "wfernandoaugusto01@gmail.com",
    sexo: "M",
    dataNascimento: "1993-07-27",
    telefone: "21966744479",
    numeroDocumento: "51602127018",
    solicitarSegundaVia: false,
    solicitarPrimeiraVia: false,
    pedidoCartao: false,
    matricula: "0004",
    valorUsoDiario: 7,
    valorUsoDiarioRefeicao: 0,
    valorAlimentacao: 0,
    valorCombustivel: 0,
    numeroLogicoMidia: 0,
    tipoDePedido: "",
    valorDaRecarga: 0,
  },
  {
    idClientePrincipal: 636,
    idPerfilClientePrincipal: 1,
    idClienteFavorecido: 638,
    idPerfilClienteFavorecido: 2,
    dataInclusao: "2023-09-26T21:07:54",
    dataCancelamento: "2023-11-08T14:25:29",
    nome: "CPF Teste 3",
    email: "teste@teste.com",
    sexo: "M",
    dataNascimento: "1993-07-27",
    telefone: "21999999999",
    numeroDocumento: "91840697083",
    solicitarSegundaVia: false,
    solicitarPrimeiraVia: false,
    pedidoCartao: false,
    matricula: "0005",
    valorUsoDiario: 2.99,
    valorUsoDiarioRefeicao: 0,
    valorAlimentacao: 0,
    valorCombustivel: 0,
    numeroLogicoMidia: 0,
    tipoDePedido: "",
    valorDaRecarga: 0,
  },
  {
    idClientePrincipal: 636,
    idPerfilClientePrincipal: 1,
    idClienteFavorecido: 849,
    idPerfilClienteFavorecido: 2,
    dataInclusao: "2023-10-20T18:41:48",
    dataCancelamento: "2023-11-08T14:25:21",
    nome: "CPF Teste 15",
    email: "",
    sexo: "M",
    dataNascimento: "1993-07-27",
    telefone: "21999999999",
    numeroDocumento: "44202348060",
    solicitarSegundaVia: false,
    solicitarPrimeiraVia: true,
    pedidoCartao: false,
    matricula: "00015",
    valorUsoDiario: 5,
    valorUsoDiarioRefeicao: 0,
    valorAlimentacao: 0,
    valorCombustivel: 0,
    numeroLogicoMidia: 0,
    tipoDePedido: "",
    valorDaRecarga: 0,
  },
  {
    idClientePrincipal: 636,
    idPerfilClientePrincipal: 1,
    idClienteFavorecido: 958,
    idPerfilClienteFavorecido: 2,
    dataInclusao: "2023-11-08T14:03:52",
    dataCancelamento: "2023-11-08T14:25:13",
    nome: "aaaaaaaaaaaaaa",
    email: "teste@teste.com",
    sexo: "M",
    dataNascimento: "1993-07-27",
    telefone: "21999999999",
    numeroDocumento: "47400711008",
    solicitarSegundaVia: false,
    solicitarPrimeiraVia: false,
    pedidoCartao: false,
    matricula: "rrr123123asdsa",
    valorUsoDiario: 15,
    valorUsoDiarioRefeicao: 0,
    valorAlimentacao: 0,
    valorCombustivel: 0,
    numeroLogicoMidia: 0,
    tipoDePedido: "",
    valorDaRecarga: 0,
  },
];

export const mockPedido = [
  {
    numero: 1442,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "PAGO",
    valorPago: 210,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-29T14:51:15",
    itensPedido: [
      {
        numeroItem: 1668,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 13,
        servico: "Crédito conta Jaé VT",
        idTipoItemPedido: 13,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1443,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 3,
    valorCalculadoPedido: 630,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-30T19:02:37",
    itensPedido: [
      {
        numeroItem: 1669,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 13,
        servico: "Crédito conta Jaé VT",
        idTipoItemPedido: 13,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
      {
        numeroItem: 1670,
        idCliente: 208,
        usuario: "Fernando Augusto Rodrigues de Almeida Azevedo",
        cartao: null,
        valor: 210,
        idServico: 13,
        servico: "Crédito conta Jaé VT",
        idTipoItemPedido: 13,
        idTipoBeeValePedido: null,
        documento: "15355251773",
        valorUsoDiario: 10,
        idProduto: 2,
      },
      {
        numeroItem: 1671,
        idCliente: 653,
        usuario: "Teste 27/09/2023",
        cartao: null,
        valor: 210,
        idServico: 13,
        servico: "Crédito conta Jaé VT",
        idTipoItemPedido: 13,
        idTipoBeeValePedido: null,
        documento: "13437440080",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 630,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1385,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 2,
    valorCalculadoPedido: 161,
    statusPedido: "PAGO",
    valorPago: 161,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-07T15:22:28",
    itensPedido: [
      {
        numeroItem: 1602,
        idCliente: 637,
        usuario: "CPF Teste ",
        cartao: null,
        valor: 147,
        idServico: 5,
        servico: "Solicitação de cartão com carga",
        idTipoItemPedido: 5,
        idTipoBeeValePedido: null,
        documento: "51602127018",
        valorUsoDiario: 7,
        idProduto: 2,
      },
      {
        numeroItem: 1603,
        idCliente: 636,
        usuario: "Empresa NOVA 01",
        cartao: null,
        valor: 14,
        idServico: 7,
        servico: "Taxa de entrega",
        idTipoItemPedido: 7,
        idTipoBeeValePedido: null,
        documento: "21369699000131",
        valorUsoDiario: 0,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 161,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 577,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1418,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 50,
    statusPedido: "PAGO",
    valorPago: 50,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-23T18:38:14",
    itensPedido: [
      {
        numeroItem: 1643,
        idCliente: 208,
        usuario: "Fernando Augusto Rodrigues de Almeida Azevedo",
        cartao: null,
        valor: 50,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "15355251773",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 50,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1419,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 25,
    statusPedido: "PAGO",
    valorPago: 25,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-23T18:48:00",
    itensPedido: [
      {
        numeroItem: 1644,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 25,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 25,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1420,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-23T18:55:56",
    itensPedido: [
      {
        numeroItem: 1645,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1388,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 300,
    statusPedido: "PAGO",
    valorPago: 300,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-08T13:18:05",
    itensPedido: [
      {
        numeroItem: 1608,
        idCliente: 208,
        usuario: "Fernando Augusto Rodrigues de Almeida Azevedo",
        cartao: null,
        valor: 300,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "15355251773",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 300,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1421,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-23T18:56:03",
    itensPedido: [
      {
        numeroItem: 1646,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1389,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 5,
    valorCalculadoPedido: 266,
    statusPedido: "PAGO",
    valorPago: 266,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-08T13:43:14",
    itensPedido: [
      {
        numeroItem: 1609,
        idCliente: 955,
        usuario: "Teste pedir cartão ",
        cartao: null,
        valor: 210,
        idServico: 5,
        servico: "Solicitação de cartão com carga",
        idTipoItemPedido: 5,
        idTipoBeeValePedido: null,
        documento: "05930789002",
        valorUsoDiario: 10,
        idProduto: 2,
      },
      {
        numeroItem: 1610,
        idCliente: 636,
        usuario: "Empresa NOVA 01",
        cartao: null,
        valor: 14,
        idServico: 7,
        servico: "Taxa de entrega",
        idTipoItemPedido: 7,
        idTipoBeeValePedido: null,
        documento: "21369699000131",
        valorUsoDiario: 0,
        idProduto: 2,
      },
      {
        numeroItem: 1611,
        idCliente: 636,
        usuario: "Empresa NOVA 01",
        cartao: null,
        valor: 14,
        idServico: 7,
        servico: "Taxa de entrega",
        idTipoItemPedido: 7,
        idTipoBeeValePedido: null,
        documento: "21369699000131",
        valorUsoDiario: 0,
        idProduto: 2,
      },
      {
        numeroItem: 1612,
        idCliente: 636,
        usuario: "Empresa NOVA 01",
        cartao: null,
        valor: 14,
        idServico: 7,
        servico: "Taxa de entrega",
        idTipoItemPedido: 7,
        idTipoBeeValePedido: null,
        documento: "21369699000131",
        valorUsoDiario: 0,
        idProduto: 2,
      },
      {
        numeroItem: 1613,
        idCliente: 636,
        usuario: "Empresa NOVA 01",
        cartao: null,
        valor: 14,
        idServico: 7,
        servico: "Taxa de entrega",
        idTipoItemPedido: 7,
        idTipoBeeValePedido: null,
        documento: "21369699000131",
        valorUsoDiario: 0,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 266,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 577,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1422,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-23T18:56:04",
    itensPedido: [
      {
        numeroItem: 1647,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1390,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-08T13:56:12",
    itensPedido: [
      {
        numeroItem: 1614,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1423,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-23T18:57:19",
    itensPedido: [
      {
        numeroItem: 1648,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1391,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 315,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-08T14:06:19",
    itensPedido: [
      {
        numeroItem: 1615,
        idCliente: 958,
        usuario: "aaaaaaaaaaaaaa",
        cartao: null,
        valor: 315,
        idServico: 5,
        servico: "Solicitação de cartão com carga",
        idTipoItemPedido: 5,
        idTipoBeeValePedido: null,
        documento: "47400711008",
        valorUsoDiario: 15,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 315,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1424,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-23T18:57:29",
    itensPedido: [
      {
        numeroItem: 1649,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1392,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-08T14:28:38",
    itensPedido: [
      {
        numeroItem: 1616,
        idCliente: 959,
        usuario: "teste pedir cartao xxxxx",
        cartao: null,
        valor: 210,
        idServico: 5,
        servico: "Solicitação de cartão com carga",
        idTipoItemPedido: 5,
        idTipoBeeValePedido: null,
        documento: "20157451062",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1425,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-23T18:57:30",
    itensPedido: [
      {
        numeroItem: 1650,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1393,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-08T14:45:03",
    itensPedido: [
      {
        numeroItem: 1617,
        idCliente: 959,
        usuario: "teste pedir cartao xxxxx",
        cartao: null,
        valor: 210,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "20157451062",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1394,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 310,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-08T15:22:47",
    itensPedido: [
      {
        numeroItem: 1618,
        idCliente: 208,
        usuario: "Fernando Augusto Rodrigues de Almeida Azevedo",
        cartao: null,
        valor: 310,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "15355251773",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 310,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1427,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "PAGO",
    valorPago: 210,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-23T19:03:34",
    itensPedido: [
      {
        numeroItem: 1652,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 13,
        servico: "Crédito conta Jaé VT",
        idTipoItemPedido: 13,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1395,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 500,
    statusPedido: "EM_PREPARO",
    valorPago: 0,
    dataPagamento: null,
    dataInclusao: "2023-11-08T15:23:24",
    itensPedido: [
      {
        numeroItem: 1619,
        idCliente: 208,
        usuario: "Fernando Augusto Rodrigues de Almeida Azevedo",
        cartao: null,
        valor: 500,
        idServico: 11,
        servico: "Crédito conta Jaé",
        idTipoItemPedido: 11,
        idTipoBeeValePedido: null,
        documento: "15355251773",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 500,
        dataPagamento: null,
        formaPagamento: "BOLETO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: null,
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: true,
    dataCancelamento: null,
  },
  {
    numero: 1428,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 176,
    statusPedido: "PAGO",
    valorPago: 176,
    dataPagamento: "2023-11-23T00:00:00",
    dataInclusao: "2023-11-23T19:22:28",
    itensPedido: [
      {
        numeroItem: 1653,
        idCliente: 208,
        usuario: "Fernando Augusto Rodrigues de Almeida Azevedo",
        cartao: null,
        valor: 176,
        idServico: 13,
        servico: "Crédito conta Jaé VT",
        idTipoItemPedido: 13,
        idTipoBeeValePedido: null,
        documento: "15355251773",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 176,
        dataPagamento: "2023-11-23T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: false,
    dataCancelamento: null,
  },
  {
    numero: 1439,
    idCliente: 636,
    nomeCliente: "Empresa NOVA 01",
    documentoCliente: "21369699000131",
    quantidadeItens: 1,
    valorCalculadoPedido: 210,
    statusPedido: "PAGO",
    valorPago: 210,
    dataPagamento: "2023-11-29T00:00:00",
    dataInclusao: "2023-11-29T14:36:03",
    itensPedido: [
      {
        numeroItem: 1665,
        idCliente: 956,
        usuario: "aaa",
        cartao: null,
        valor: 210,
        idServico: 13,
        servico: "Crédito conta Jaé VT",
        idTipoItemPedido: 13,
        idTipoBeeValePedido: null,
        documento: "52508376035",
        valorUsoDiario: 10,
        idProduto: 2,
      },
    ],
    pagamentosPedido: [
      {
        valorPago: 210,
        dataPagamento: "2023-11-29T00:00:00",
        formaPagamento: "DEPOSITO",
        identificador: null,
        dataBaixa: null,
        tipoBaixa: "ESPECIAL",
        usuario: null,
      },
    ],
    nrSeqEndereco: 0,
    podeExcluir: false,
    dataCancelamento: null,
  },
];

export const mockStatusPedido = [
  {
    label: "Aguardando pagamento",
    value: "AGUARDANDO_PAGAMENTO",
    color: "text-yellow-500",
  },
  { label: "Pago", value: "PAGO", color: "text-green-500" },
  { label: "Em preparo", value: "EM_PREPARO", color: "text-gray-500" },
  {
    label: "Pago com diferença",
    value: "PAGO_COM_DIFERENÇA",
    color: "text-blue-500",
  },
  { label: "Em produção", value: "EM_PRODUÇÃO", color: "text-yellow-500" },
  { label: "Concluído", value: "CONCLUIDO", color: "text-green-500" },
  { label: "Cancelado", value: "CANCELADO", color: "text-red-500" },
  { label: "Produzido", value: "PRODUZIDO", color: "text-blue-500" },
];

export const mockUsuario = {
  jti: "da02a553-d6dc-473e-aab2-21d1eb0e2ab9",
  sub: "21369699000131",
  nome: "Empresa NOVA 01",
  perfis: ["EMPRESA"],
  email: "wfernandoaugusto01@gmail.com",
  iat: 1701692413,
  iss: "",
  exp: 1733228413,
  idCliente: null,
  codigo: 636,
  enderecos: [
    {
      nrSeqEndereco: 577,
      logradouro: "Rua Conde de Bonfim",
      complemento: "Bloco B - 501",
      bairro: "Tijuca",
      cidade: "Rio de Janeiro",
      uf: "RJ",
      cep: "20530001",
      numero: "1325",
      dataCadastro: "2023-09-26",
      dataInativacao: null,
      latitude: null,
      longitude: null,
      tipoEndereco: null,
      tipoLogradouro: null,
    },
  ],
  numeroDocumento: "21369699000131",
  telefone: "21966744479",
  tipoDocumento: {
    codigo: 2,
    descricao: null,
  },
  senha: "",
  confirmacaoSenha: "",
  servicoRequisicao: false,
  idTipoPerfilCliente: 1,
  autorizadoRequisicao: false,
  tipoGeracaoFatura: "SEMANAL",
  tipoPagamento: "DEPOSITO",
};

export const mockLojas = [
  {
    codigo: 3,
    nome: "Loja Desenv",
    numeroDocumento: "91666822000161",
    idContaAcesso: null,
    tipoDocumento: {
      codigo: null,
      descricao: null,
    },
    tipoPessoa: "J",
    email: "everaldo.cartaxo@billingpay.com.br",
    telefone: "21970380103",
    dataCadastro: "2022-04-04",
    enderecos: [
      {
        nrSeqEndereco: 502,
        logradouro: "Rua Uruguaiana",
        complemento: "9o. andar",
        bairro: "Centro",
        cidade: "Rio de Janeiro",
        uf: "RJ",
        cep: "20050900",
        numero: "172",
        dataInativacao: null,
      },
    ],
    tiposDePerfis: ["LOJA"],
    nomeMae: null,
    nomePai: null,
    sexo: null,
    jsonIntegracao: null,
    numeroCartaoOperador: null,
  },
  {
    codigo: 51,
    nome: "Loja Jaé - Central do Brasil",
    numeroDocumento: "26464846000176",
    idContaAcesso: null,
    tipoDocumento: {
      codigo: null,
      descricao: null,
    },
    tipoPessoa: "J",
    email: "everaldo.cartaxo@billingpay.com.br",
    telefone: "21970380103",
    dataCadastro: "2022-07-06",
    enderecos: [
      {
        nrSeqEndereco: 210,
        logradouro: "Praça Cristiano Ottoni",
        complemento: "",
        bairro: "Centro",
        cidade: "Rio de Janeiro",
        uf: "RJ",
        cep: "20080102",
        numero: "S/N",
        dataInativacao: null,
      },
      {
        nrSeqEndereco: 501,
        logradouro: "Praça Cristiano Ottoni",
        complemento: "",
        bairro: "Centro",
        cidade: "Rio de Janeiro",
        uf: "RJ",
        cep: "20080102",
        numero: "",
        dataInativacao: null,
      },
    ],
    tiposDePerfis: ["LOJA"],
    nomeMae: null,
    nomePai: null,
    sexo: null,
    jsonIntegracao:
      '{"gerencia_loja":{"codEmp": "0001", "codFil": "0001", "numCcoOrigem": "CX_GERAL", "numCcoDestino": "CUSTODIA001"}, "loja":{"codEmp": "0001", "codFil": "0001", "numCcoOrigem": "GUICHE00001", "numCcoDestino": "CX_GERAL"}}',
    numeroCartaoOperador: null,
  },
  {
    codigo: 454,
    nome: "Loja Desenv 2",
    numeroDocumento: "19507828000169",
    idContaAcesso: null,
    tipoDocumento: {
      codigo: null,
      descricao: null,
    },
    tipoPessoa: "J",
    email: "thiago.miguel@billingpay.com.br",
    telefone: "21982892176",
    dataCadastro: "2023-07-13",
    enderecos: [
      {
        nrSeqEndereco: 524,
        logradouro: "Estrada Camboatá",
        complemento: "12",
        bairro: "Guadalupe",
        cidade: "Rio de Janeiro",
        uf: "RJ",
        cep: "21660005",
        numero: "3016",
        dataInativacao: null,
      },
    ],
    tiposDePerfis: ["LOJA"],
    nomeMae: null,
    nomePai: null,
    sexo: null,
    jsonIntegracao: null,
    numeroCartaoOperador: null,
  },
  {
    codigo: 468,
    nome: "Mobi Rio",
    numeroDocumento: "35330082000117",
    idContaAcesso: null,
    tipoDocumento: {
      codigo: null,
      descricao: null,
    },
    tipoPessoa: "J",
    email: "ronaldosoaresqueiroz@gmail.com",
    telefone: "21995843710",
    dataCadastro: "2023-07-15",
    enderecos: [
      {
        nrSeqEndereco: 528,
        logradouro: "Rua Esperança",
        complemento: "casa 104",
        bairro: "Vargem Grande",
        cidade: "Rio de Janeiro",
        uf: "RJ",
        cep: "22785590",
        numero: "55",
        dataInativacao: null,
      },
    ],
    tiposDePerfis: ["LOJA"],
    nomeMae: null,
    nomePai: null,
    sexo: null,
    jsonIntegracao: null,
    numeroCartaoOperador: null,
  },
  {
    codigo: 471,
    nome: "Loja Arterius",
    numeroDocumento: "60935058000159",
    idContaAcesso: null,
    tipoDocumento: {
      codigo: null,
      descricao: null,
    },
    tipoPessoa: "J",
    email: "thiago.miguel@billingpay.com.br",
    telefone: "21982892176",
    dataCadastro: "2023-07-18",
    enderecos: [
      {
        nrSeqEndereco: 529,
        logradouro: "Estrada Camboatá",
        complemento: "",
        bairro: "Guadalupe",
        cidade: "Rio de Janeiro",
        uf: "RJ",
        cep: "21660005",
        numero: "S N",
        dataInativacao: null,
      },
    ],
    tiposDePerfis: ["LOJA"],
    nomeMae: null,
    nomePai: null,
    sexo: null,
    jsonIntegracao: null,
    numeroCartaoOperador: null,
  },
];
